NiceGUI ready to go on http://localhost:8080, http://192.168.1.154:8080, and http://192.168.2.1:8080
Traceback (most recent call last):
  File "/Users/samihalawa/git/CLONED_REPOS_MASTER/TOOLS_MASTER/macos-optimizer1/gui/src/python-app-nicegui.py", line 1455, in <module>
    run(playwright)
  File "/Users/samihalawa/git/CLONED_REPOS_MASTER/TOOLS_MASTER/macos-optimizer1/gui/src/python-app-nicegui.py", line 1448, in run
    page = browser.new_page()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/.pyenv/versions/3.11.10/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 14155, in new_page
    self._sync(
  File "/Users/samihalawa/.pyenv/versions/3.11.10/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/samihalawa/.pyenv/versions/3.11.10/lib/python3.11/site-packages/playwright/_impl/_browser.py", line 181, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/.pyenv/versions/3.11.10/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Browser.new_page: Target page, context or browser has been closed
